# This is a basic workflow to help you get started with Actions

name: GH Actions Snyk Scan

on: workflow_dispatch

env:
  zone: us-central1-c
  machineType: e2-highcpu-4 
  releaseName: datadog-agent  

jobs:
 GCR-Run:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        #version: '290.0.1'
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    #- run: gcloud container clusters create ${{secrets.GKE_CLUSTER_NAME}} --zone=${{ env.zone }} --machine-type=${{ env.machineType }}
    - name: Run Snyk to check Docker images for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: gcr.io/jamieo4626/goof
    
