name: Private GCR Snyk Scan gcLoud SDK

on: workflow_dispatch

jobs:
 GCR-Run:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #- name: step 2
    - uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    - run: gcloud auth configure-docker https://gcr.io
    - name: Run Snyk to check Docker images for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: gcr.io/jamieo4626/goof
